include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Error prevention
    - avoid_empty_else
    - avoid_print
    - await_only_futures
    - cancel_subscriptions
    - close_sinks
    - control_flow_in_finally
    - empty_statements
    - hash_and_equals
    - throw_in_finally
    - unrelated_type_equality_checks
    - valid_regexps

    # Style & Clarity
    - always_declare_return_types
    - avoid_shadowing_type_parameters
    - camel_case_types
    - directives_ordering
    - empty_catches
    - file_names
    - library_names
    - library_prefixes
    - no_duplicate_case_values
    - null_closures
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_final_locals
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_single_quotes
    - recursive_getters
    - slash_for_doc_comments
    - type_init_formals
    - unawaited_futures
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_new
    - unnecessary_this

analyzer:
  language:
    strict-casts: true
    strict-inference: true
